version: '3.8'

services:
  # PostgreSQL Database para desarrollo
  postgres:
    image: postgres:15-alpine
    container_name: pulso-ai-postgres
    environment:
      POSTGRES_DB: pulso_ai_dev
      POSTGRES_USER: pulso_ai
      POSTGRES_PASSWORD: dev_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=es_ES.UTF-8 --lc-ctype=es_ES.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - pulso-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulso_ai -d pulso_ai_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para caching y sessions
  redis:
    image: redis:7-alpine
    container_name: pulso-ai-redis
    command: redis-server --appendonly yes --requirepass dev_redis_2024
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pulso-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer para database management (opcional)
  adminer:
    image: adminer:4.8.1
    container_name: pulso-ai-adminer
    ports:
      - "8080:8080"
    networks:
      - pulso-ai-network
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - admin

  # Redis Commander para Redis management (opcional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pulso-ai-redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:dev_redis_2024
    networks:
      - pulso-ai-network
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - admin

# Volumes para persistencia de datos
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# Network para comunicación entre servicios
networks:
  pulso-ai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
